In [1]:
import numpy as np

In [4]:
## Array slicing and indexing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr)

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
print(arr[0][0])

1


In [9]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [10]:
## Modify array elements

arr[0,0] = 100
arr

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [13]:
## statistical concept -- Normalization
# to have a mean of 0 and standard deviation of 1

data = np.array([1,2,3,4,5])

## Calculate the mean and standard deviation

mean = np.mean(data)
std_dev = np.std(data)

# normalized data 

normalized_data = (data  - mean) / std_dev

print("Normmalized data : ", normalized_data)


Normmalized data :  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [17]:
data = [1,2,3,4,5,6,7,8,9,10]

#mean
mean = np.mean(data)
print("Mean :", mean)

# median
med = np.median(data)
print("Median :", med)

# standard deviation

std_dev = np.std(data)
print("Standard_deviation :", std_dev)

# variance
var = np.var(data)
print("variance : ", var)


Mean : 5.5
Median : 5.5
Standard_deviation : 2.8722813232690143
variance :  8.25


In [19]:
## Logical Operation

data = np.array([1,2,3,4,5,6,7,8,9,10])

data[data>5]

array([ 6,  7,  8,  9, 10])